### ISSUE TITLE
Add text decoration underline on links

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/raft#40]
### What problem does this address?

Links are not currently emphasized in any way, so they are hard to be spotted, only the cursor changes when hovering over them.

### What is your proposed solution?

Add text decoration underline on links like we have in Neve.

Requested here: https://secure.helpscout.net/conversation/2200852455/363944/

**Comment by mghenciu** [comment]
> https://github.com/orgs/Codeinwp/teams/design-team Just to confirm, do you have any input here before we go ahead with it?

The request makes sense, also from an Accessibility pov.
The challenge we had with this before, is that **there are cases when as a user/designer - you will not want those underlines visible**. One example is when having a Posts Grid, and each title is a link - in this case the underline makes things look bad.

So if we go for this, **I would use the Core 2023 theme as a reference** - since they improved some of the things I mentioned above (example below), compared to 2022 - and not just applying the underline everywhere: 
![Screenshot 2023-04-19 at 14 46 09](https://user-images.githubusercontent.com/52494172/233065548-48f48ba3-7eba-4172-9cf8-983c74b12df0.png)

**Comment by HardeepAsrani** [comment]
Thank you @mghenciu, we will keep that in mind.
